config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :revists
  resources :enologos
  resources :cepas
  resources :vinos
  
  root 'vinos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cepa.rb
class Cepa < ApplicationRecord
    has_many :vino_cepas
    has_many :vinos, through: :vino_cepas, dependent: :destroy 

    validates :nombre, presence: true, allow_blank: false
    validates :nombre, uniqueness: { case_sensitive: true }
    
end

app/controllers/cepas_controller.rb
class CepasController < ApplicationController
  before_action :set_cepa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cepas
  # GET /cepas.json
  def index
    @cepas = Cepa.all
  end

  # GET /cepas/1
  # GET /cepas/1.json
  def show
  end

  # GET /cepas/new
  def new
    @cepa = Cepa.new
  end

  # GET /cepas/1/edit
  def edit
  end

  # POST /cepas
  # POST /cepas.json
  def create
    @cepa = Cepa.new(cepa_params)

    respond_to do |format|
      if @cepa.save
        format.html { redirect_to @cepa, notice: 'Cepa was successfully created.' }
        format.json { render :show, status: :created, location: @cepa }
      else
        format.html { render :new }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cepas/1
  # PATCH/PUT /cepas/1.json
  def update
    respond_to do |format|
      if @cepa.update(cepa_params)
        format.html { redirect_to @cepa, notice: 'Cepa was successfully updated.' }
        format.json { render :show, status: :ok, location: @cepa }
      else
        format.html { render :edit }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cepas/1
  # DELETE /cepas/1.json
  def destroy
    @cepa.destroy
    respond_to do |format|
      format.html { redirect_to cepas_url, notice: 'Cepa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cepa
      @cepa = Cepa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cepa_params
      params.require(:cepa).permit(:nombre, :proporcion)
    end
end

app/helpers/cepas_helper.rb
module CepasHelper
end

app/views/cepas/_form.html.erb
<%= form_with(model: cepa, local: true) do |form| %>
  <% if cepa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cepa.errors.count, "error") %> prohibited this cepa from being saved:</h2>

      <ul>
      <% cepa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :proporcion %>
    <%= form.text_field :proporcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cepas/edit.html.erb
<h1>Editing Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Show', @cepa %> |
<%= link_to 'Back', cepas_path %>

app/views/cepas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cepas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Proporcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cepas.each do |cepa| %>
      <tr>
        <td><%= cepa.nombre %></td>
        <td><%= cepa.proporcion %></td>
        <% if current_user.admi?%>
          <td><%= link_to 'Show', cepa %></td>
          <td><%= link_to 'Edit', edit_cepa_path(cepa) %></td>
          <td><%= link_to 'Destroy', cepa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admi?%>
<%= link_to 'New Cepa', new_cepa_path %>
<%end%>

app/views/cepas/new.html.erb
<h1>New Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Back', cepas_path %>

app/views/cepas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cepa.nombre %>
</p>

<p>
  <strong>Proporcion:</strong>
  <%= @cepa.proporcion %>
</p>

<%= link_to 'Edit', edit_cepa_path(@cepa) %> |
<%= link_to 'Back', cepas_path %>