config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :revists
  resources :enologos
  resources :cepas
  resources :vinos
  
  root 'vinos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/revist.rb
class Revist < ApplicationRecord
    has_many :enologo_revists
    has_many :enologos, through: :enologo_revists, dependent: :destroy 
end

app/controllers/revists_controller.rb
class RevistsController < ApplicationController
  before_action :set_revist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /revists
  # GET /revists.json
  def index
    @revists = Revist.all
  end

  # GET /revists/1
  # GET /revists/1.json
  def show
  end

  # GET /revists/new
  def new
    @revist = Revist.new
  end

  # GET /revists/1/edit
  def edit
  end

  # POST /revists
  # POST /revists.json
  def create
    @revist = Revist.new(revist_params)

    respond_to do |format|
      if @revist.save
        format.html { redirect_to @revist, notice: 'Revist was successfully created.' }
        format.json { render :show, status: :created, location: @revist }
      else
        format.html { render :new }
        format.json { render json: @revist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revists/1
  # PATCH/PUT /revists/1.json
  def update
    respond_to do |format|
      if @revist.update(revist_params)
        format.html { redirect_to @revist, notice: 'Revist was successfully updated.' }
        format.json { render :show, status: :ok, location: @revist }
      else
        format.html { render :edit }
        format.json { render json: @revist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revists/1
  # DELETE /revists/1.json
  def destroy
    @revist.destroy
    respond_to do |format|
      format.html { redirect_to revists_url, notice: 'Revist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revist
      @revist = Revist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def revist_params
      params.require(:revist).permit(:nombre)
    end
end

app/helpers/revists_helper.rb
module RevistsHelper
end

app/views/revists/_form.html.erb
<%= form_with(model: revist, local: true) do |form| %>
  <% if revist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(revist.errors.count, "error") %> prohibited this revist from being saved:</h2>

      <ul>
      <% revist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/revists/edit.html.erb
<h1>Editing Revist</h1>

<%= render 'form', revist: @revist %>

<%= link_to 'Show', @revist %> |
<%= link_to 'Back', revists_path %>

app/views/revists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Revists</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @revists.each do |revist| %>
      <tr>
        <td><%= revist.nombre %></td>
        <% if current_user.admi?%>
          <td><%= link_to 'Show', revist %></td>
          <td><%= link_to 'Edit', edit_revist_path(revist) %></td>
          <td><%= link_to 'Destroy', revist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admi?%>
  <%= link_to 'New Revist', new_revist_path %>
<%end%>

app/views/revists/new.html.erb
<h1>New Revist</h1>

<%= render 'form', revist: @revist %>

<%= link_to 'Back', revists_path %>

app/views/revists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @revist.nombre %>
</p>
<% if current_user.admi?%>
  <%= link_to 'Edit', edit_revist_path(@revist) %> |
<%end%>
<br>
  <%= link_to 'Back', revists_path %>