config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :revists
  resources :enologos
  resources :cepas
  resources :vinos
  
  root 'vinos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vino.rb
class Vino < ApplicationRecord
    has_many :vino_cepas, dependent: :destroy 
    has_many :cepas, through: :vino_cepas, dependent: :destroy 
    has_many :vino_enologos, dependent: :destroy 
    has_many :enologos, through: :vino_enologos, dependent: :destroy 

    accepts_nested_attributes_for :vino_enologos

    validates :nota,   numericality: {  greater_than_or_equal_to: 1, less_than_or_equal_to: 100,  only_integer: true }
    
end

app/controllers/vinos_controller.rb
class VinosController < ApplicationController
  before_action :set_vino, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /vinos
  # GET /vinos.json
  def index
    @vinos = Vino.all
  end

  # GET /vinos/1
  # GET /vinos/1.json
  def show
  end

  # GET /vinos/new
  def new
    @vino = Vino.new
    @vino_enologos = VinoEnologo.new
  end

  # GET /vinos/1/edit
  def edit
  end

  # POST /vinos
  # POST /vinos.json
  def create
    @vino = Vino.new(vino_params)
    #@vino_enologo = VinoEnologo.new(nota: params[:vino_enologo][:nota])

    respond_to do |format|
      if @vino.save
        # @vino_enologo.nota 
        # @vino_enologo.save!
        # @vino.save!
        format.html { redirect_to @vino, notice: 'Vino was successfully created.' }
        format.json { render :show, status: :created, location: @vino }
      else
        format.html { render :new }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinos/1
  # PATCH/PUT /vinos/1.json
  def update
    respond_to do |format|
      if @vino.update(vino_params)
        format.html { redirect_to @vino, notice: 'Vino was successfully updated.' }
        format.json { render :show, status: :ok, location: @vino }
      else
        format.html { render :edit }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinos/1
  # DELETE /vinos/1.json
  def destroy
    @vino.destroy
    respond_to do |format|
      format.html { redirect_to vinos_url, notice: 'Vino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vino
      @vino = Vino.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vino_params
      params.require(:vino).permit(:nombre, { cepa_ids: []}, { enologo_ids: []}, :nota)
    end
end

app/helpers/vinos_helper.rb
module VinosHelper
end

app/views/vinos/_form.html.erb
<%= form_with(model: vino, local: true) do |form| %>
  <% if vino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vino.errors.count, "error") %> prohibited this vino from being saved:</h2>

      <ul>
      <% vino.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
  <div class="field">
    <%= form.label :cepas %>
    <%= form.collection_check_boxes(:cepa_ids, Cepa.all, :id, :nombre )do |b| %>
      <%= b.label class:"label-checkbox" do%>
      <%=b.check_box + b.text %>
      <%= form.select :cepas_ids, Cepa.all.collect { |b| [ b.proporcion, b.id ]  } %>
      <%end%>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :enologos %>
    <%= form.collection_check_boxes(:enologo_ids, Enologo.all, :id, :nombre )do |b| %>
      <%= b.label class:"label-checkbox" do%>
      <%=b.check_box + b.text %>
      <%end%>
    <% end %>
  </div>
  <%#= fields_for :vino_enologos do |f| %>
  <%# <div class="field"> %>
      <%#= f.number_field :nota%>
  <%# </div> %>
  <%#end%>
  <div class="field">
    <%= form.label :nota %>
    <%= form.number_field :nota %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vinos/edit.html.erb
<h1>Editing Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Show', @vino %> |
<%= link_to 'Back', vinos_path %>

app/views/vinos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vinos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre del vino</th>
      <th>Cepa y proporción( )</th>
      <th>Enólogo</th>
      <th>Nota (1-100)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vinos.each do |vino| %>
      <tr>
        <td><%= vino.nombre %></td>
        <td><ul> <% vino.cepas.order("nombre ASC").each do |cepa| %>
                    <li><%=cepa.nombre %> (<%=cepa.proporcion %>%)</li> 
                 <%end%><br>
        </ul></td>
  
        <td><ul>
          <% vino.enologos.order("edad DESC").each do |enologo| %>
            <li><%=enologo.nombre %> (<%=enologo.edad %>)</li> 
          <%end%>
        <br></ul></td>
        <td><%= vino.nota %></td>
        <% if current_user.admi?%>
          <td><%= link_to 'Show', vino %></td>
          <td><%= link_to 'Edit', edit_vino_path(vino) %></td>
          <td><%= link_to 'Destroy', vino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admi?%>
  <%= link_to 'New Vino', new_vino_path %>
 <%end%>

app/views/vinos/new.html.erb
<h1>New Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Back', vinos_path %>

app/views/vinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @vino.nombre %>
</p>
<p> <strong>Nota:</strong>
  <%= @vino.nota %>
</p>

<% if current_user.admi?%>
  <%= link_to 'Edit', edit_vino_path(@vino) %> |
<%end%>
  <%= link_to 'Back', vinos_path %>