config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :revists
  resources :enologos
  resources :cepas
  resources :vinos
  
  root 'vinos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enologo.rb
class Enologo < ApplicationRecord
    has_many :vino_enologos
    has_many :vinos, through: :vino_enologos, dependent: :destroy 
    has_many :enologo_revists
    has_many :revists, through: :enologo_revists, dependent: :destroy 

    accepts_nested_attributes_for :enologo_revists
end

app/controllers/enologos_controller.rb
class EnologosController < ApplicationController
  before_action :set_enologo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /enologos
  # GET /enologos.json
  def index
    @enologos = Enologo.all
  end

  # GET /enologos/1
  # GET /enologos/1.json
  def show
  end

  # GET /enologos/new
  def new
    @enologo = Enologo.new
  end

  # GET /enologos/1/edit
  def edit
  end

  # POST /enologos
  # POST /enologos.json
  def create
    @enologo = Enologo.new(enologo_params)
    @enologo_revist = EnologoRevist.new( revist_id: params[:enologo_revist][:revist_id], cargo: params[:enologo_revist][:cargo])

    respond_to do |format|
      if @enologo.save
        @enologo_revist.enologo_id = @enologo.id
        @revist = Revist.find_by(params[:revist_id])
        @enologo_revist.revist_id = @revist.id
        @enologo_revist.save!
        @enologo.save!
        format.html { redirect_to @enologo, notice: 'Enologo was successfully created.' }
        format.json { render :show, status: :created, location: @enologo }
      else
        format.html { render :new }
        format.json { render json: @enologo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologos/1
  # PATCH/PUT /enologos/1.json
  def update
    respond_to do |format|
      if @enologo.update(enologo_params)
       
        format.html { redirect_to @enologo, notice: 'Enologo was successfully updated.' }
        format.json { render :show, status: :ok, location: @enologo }
      else
        format.html { render :edit }
        format.json { render json: @enologo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologos/1
  # DELETE /enologos/1.json
  def destroy
    @enologo.destroy
    respond_to do |format|
      format.html { redirect_to enologos_url, notice: 'Enologo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologo
      @enologo = Enologo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologo_params
      params.require(:enologo).permit(:nombre, :edad, :nacionalidad, { revist_ids: []})
      
    end
end

app/helpers/enologos_helper.rb
module EnologosHelper
end

app/views/enologos/_form.html.erb
<%= form_with(model: enologo, local: true) do |form| %>
  <% if enologo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologo.errors.count, "error") %> prohibited this enologo from being saved:</h2>

      <ul>
      <% enologo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :nacionalidad %>
    <%= form.text_field :nacionalidad %>
  </div>
 
    <div class="field">
      <%= form.label :revist, 'Revista' %>
      <%= form.collection_check_boxes(:revist_ids, Revist.all, :id, :nombre) do |b| %>
        <%= b.label class:"label-checkbox" do%>
          <%=b.check_box + b.text %>
         <%= fields_for :enologo_revist do |f| %>
        <%= f.select :cargo, options_for_select(['Editor', 'Writer', 'Reviewer'])%>
        <%end%>
      <%end%>
    </div>
  <%end%>

    
  
  <div class="actions">
    <%= form.submit %>
  </div>
 
<% end %>

app/views/enologos/edit.html.erb
<h1>Editing Enologo</h1>

<%= render 'form', enologo: @enologo %>

<%= link_to 'Show', @enologo %> |
<%= link_to 'Back', enologos_path %>

app/views/enologos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Nacionalidad</th>
      <th>Revista</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologos.each do |enologo| %>
      <tr>
        <td><%= enologo.nombre %></td>
        <td><%= enologo.edad %></td>
        <td><%= enologo.nacionalidad %></td>
        <td><% enologo.enologo_revists.each do |revista|%> 
          <ul>
          <li><%=revista.revist.nombre%></li> 
         <br></ul>
         <%end%></td>
        <td><ul><% enologo.enologo_revists.each do |revista|%> 
            <%=revista.cargo%>  
        <%end%><br></ul></td>
        <%# if current_user.admi?%>
          <td><%= link_to 'Show', enologo %></td>
          <td><%= link_to 'Edit', edit_enologo_path(enologo) %></td>
          <td><%= link_to 'Destroy', enologo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%#end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%# if current_user.admi?%>
  <%= link_to 'New Enologo', new_enologo_path %>
<%#end%>

app/views/enologos/new.html.erb
<h1>New Enologo</h1>

<%= render 'form', enologo: @enologo %>

<%= link_to 'Back', enologos_path %>

app/views/enologos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @enologo.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @enologo.edad %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @enologo.nacionalidad %>
</p>

<p>
  <strong>Revista(s):</strong> <br>
  <% @enologo.enologo_revists.each do |enologo|%>
      <%= enologo.revist.nombre %>
</p>
<%end%>
<p>
  <strong>Cargo:</strong>
<% @enologo.enologo_revists.each do |enologo|%>
  <%= enologo.cargo %>
</p>
<%end%>
<% if current_user.admi?%>
  <%= link_to 'Edit', edit_enologo_path(@enologo) %>
<%end%>
<%= link_to 'Back', enologos_path %>